---
title: "Asthma vs tree"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    theme: spacelab
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(tidyverse)
library(plotly)
library(readxl)
library(shiny)
library(rgdal)
library(leaflet)
library(raster)

mydat = rgdal::readOGR(dsn ="./UHF42", layer = "UHF_42_DOHMH")


tree_df = read_csv("./data/2015StreetTreesCensus_TREES.csv") %>%
  dplyr::select(-health) %>%
  janitor::clean_names() 

zipcode_uhf42 = read_excel("./data/Zipcode_UHF42.xlsx") %>%
   gather(key = zipcode_no, value = zipcode, zipcode1:zipcode9) %>%
   dplyr::select(-zipcode_no, uhf42_name) %>%
   filter(is.na(zipcode) == FALSE)
area=data.frame(uhf42_code = mydat$UHFCODE,area = mydat$SHAPE_Area) %>%
  filter(is.na(uhf42_code) == FALSE)

tree_df =  left_join(tree_df, zipcode_uhf42, by = "zipcode") 
tree_df = left_join(tree_df, area, by = "uhf42_code")


Birch = tree_df %>%
  filter(str_detect(spc_common, "[Bb]irch")) %>%
  mutate(spc_common = "Birch") %>%
  group_by(uhf42_name, spc_common, area, uhf42_code) %>%
  dplyr::summarize(total = n())  %>%
  filter(is.na(uhf42_name) == FALSE)

Ash =  tree_df %>%
  filter(str_detect(spc_common, "[Aa]sh")) %>%
  mutate(spc_common = "Ash") %>%
  group_by(uhf42_name, spc_common, area, uhf42_code) %>%
  dplyr::summarize(total = n())  %>%
  filter(is.na(uhf42_name) == FALSE)

Oak =  tree_df %>%
  filter(str_detect(spc_common, "[Oo]ak")) %>%
  mutate(spc_common = "Oak") %>%
  group_by(uhf42_name, spc_common, area, uhf42_code) %>%
  dplyr::summarize(total = n())  %>%
  filter(is.na(uhf42_name) == FALSE)

Other = tree_df %>%
  filter(!str_detect(spc_common, "[Bb]irch") | str_detect(spc_common, "[Aa]sh") | str_detect(spc_common, "[Oo]ak")) %>%
  mutate(spc_common = "Other") %>%
  group_by(uhf42_name, spc_common, area, uhf42_code) %>%
  dplyr::summarize(total = n())  %>%
  filter(is.na(uhf42_name) == FALSE)

Total = tree_df %>%
  group_by(uhf42_name, area,uhf42_code) %>%
  dplyr::summarize(total = n()) %>%
  mutate(spc_common = "Total") %>%
  filter(is.na(uhf42_name) == FALSE)

tree_total_uhf42 = 
  bind_rows(Birch, Ash, Oak, Other, Total) %>%
  group_by(spc_common) %>%
  mutate(tree_density = total/area, 
         uhf42_name = forcats::fct_reorder(uhf42_name, tree_density)) %>% 
  mutate(tree_density = tree_density * 10000000)

health_state = c("Birch", "Ash", "Oak", "Other", "Total")

mydat2 = rgdal::readOGR(dsn ="./UHF42", layer = "UHF_42_DOHMH"")

names(mydat2)
mydat2$UHFCODE
proj4string1 =  "+proj=longlat +datum=NAD83 +no_defs +ellps=GRS80
+towgs84=0,0,0" 
mydat2 = spTransform(mydat, proj4string1)
proj4string(mydat2)


#import and tidy tree data
tree_df = read_csv("./data/2015StreetTreesCensus_TREES.csv") %>%
  janitor::clean_names() %>%
  filter(status == "Alive") 

zipcode_uhf42 = read_excel("./data/Zipcode_UHF42.xlsx") %>%
   gather(key = zipcode_no, value = zipcode, zipcode1:zipcode9) %>%
   dplyr::select(-zipcode_no, uhf42_name) %>%
   filter(is.na(zipcode) == FALSE)

tree_df = left_join(tree_df, zipcode_uhf42, by = "zipcode") 

mydat = rgdal::readOGR("./UHF42/UHF_42_DOHMH.shp")

area=data.frame(uhf42_code = mydat$UHFCODE,area = mydat$SHAPE_Area) %>%
  filter(is.na(uhf42_code) == FALSE)

tree_df = left_join(tree_df, area, by = "uhf42_code")


#tree density
tree_density = tree_df %>%
  group_by(boroname, uhf42_name, uhf42_code, area) %>%
  dplyr::summarize(tree_total = n()) %>%
  filter(is.na(uhf42_name) == FALSE) %>%
  group_by(uhf42_name) %>%
  dplyr::mutate(tree_density = tree_total/area) %>%
  ungroup() %>%
  mutate(uhf42_name = forcats::fct_reorder(uhf42_name, tree_density))


#read and tidy data
asthma_air_poverty = read_csv("./data/asthma_pollutes_poverty.csv") %>%
  dplyr::select(geo_entity_id, geo_entity_name, name, data_value) %>%
  filter(is.na(geo_entity_id) == FALSE) %>%
  spread(key = name, value = data_value) %>%
  janitor::clean_names() %>%
  dplyr::select(poverty, children_under_5_years_old_in_poverty, everything()) %>%
  mutate(asthma_total = asthma_emergency_department_visits_children_0_to_4_yrs_old + asthma_emergency_department_visits_children_5_to_14_yrs_old,
         geo_entity_name = forcats::fct_reorder(geo_entity_name, asthma_total))

tree_density_total = tree_density %>%
  dplyr::select(boroname, geo_entity_id=uhf42_code, tree_density) %>%
  distinct()

final_df = left_join(asthma_air_poverty, tree_density_total)

final_asthma_df = gather(final_df, key = asthma_age, value = rate, asthma_emergency_department_visits_children_0_to_4_yrs_old:asthma_emergency_department_visits_children_5_to_14_yrs_old) %>%
  gather(key = poverty_age, value = poverty, poverty:children_under_5_years_old_in_poverty) %>%
  filter((asthma_age == "asthma_emergency_department_visits_children_5_to_14_yrs_old"&poverty_age == "poverty")|(asthma_age == "asthma_emergency_department_visits_children_0_to_4_yrs_old"& poverty_age == "children_under_5_years_old_in_poverty"))
names(final_asthma_df)

theme_set(theme_bw())
```


Sidebar {.sidebar}
-----------------------------------------------------------------------
Choose total number or three certain trees can aggravate respiratory allergies
```{r}
# selectInput widget
selectInput("spe_choice", label = h3("Tree Species"),
            choices = health_state, selected = "Total")
```

```{r}
radioButtons("air_quality", label = h3("Air Quality Type:"),
                 list("Sulfur Dioxide" = "sulfur_dioxide_so2",
                      "Ozone" = "ozone_o3",
                      "PM2.5" = "fine_particulate_matter_pm2_5",
                      "Nitric Oxide" = "nitric_oxide_no",
                      "Black Carbon" = "black_carbon",
                      "Nitrogen Dioxide" = "nitrogen_dioxide_no2"))
```




Column {data-width=450}
-----------------------------------------------------------------------

### Tree distribution in New York

```{r}


renderLeaflet({
  total_tree = tree_total_uhf42 %>%
  filter(spc_common == input$spe_choice) %>%
  dplyr::select(UHFCODE= uhf42_code, everything()) %>%
  arrange(UHFCODE)

names(mydat2)


pal <- colorBin("Greens", total_tree$tree_density, 5, pretty = FALSE)

leaflet() %>% 
addProviderTiles("OpenStreetMap.Mapnik") %>%
setView(lat = 40.7, lng = -74, zoom = 11) %>%
addPolygons(data = mydat2, fillColor = ~pal(total_tree$tree_density), weight = 1,
  opacity = 1,
  color = "white",
  dashArray = "3",
  fillOpacity = 0.65, 
  popup = paste("Region: ", total_tree$uhf42_name, "<br>",
                          "Number: ", total_tree$total, "<br>")) %>%
  addLegend(position = "bottomright", pal = pal, values =total_tree$tree_density,
          title = "Tree density",
          opacity = 1, bins = F)
})

```

Column {data-width=350}
-----------------------------------------------------------------------

### Asthma and Tree

```{r}

renderPlotly({
bfigure =  ggplot(final_asthma_df) +
  geom_point(aes(x = tree_density, y = rate, color = asthma_age)) +
   geom_smooth(aes(x = tree_density, y = rate, color = asthma_age), method = "lm",se = F) +
   labs(
    title = "Asthma and Tree Density",
    x = "Tree Density",
    y = "Asthma Rate"
  ) +
   theme(legend.position='none') +
   guides(color = guide_legend(nrow = 2)) +
   scale_color_hue(name = "Age")

ggplotly(bfigure)

})


```

### Tree Density and Sulfur Dioxide

```{r}
renderPlotly({
cfigure = ggplot(final_asthma_df) +
  geom_point(aes_string(x = input$air_quality, y = "tree_density")) +
  geom_smooth(aes_string(x = input$air_quality, y = "tree_density"), method = "lm", se = F, color = "#2c7fb8") +
   labs(
    x = input$air_quality,
    y = "Tree Density"
  ) 

ggplotly(cfigure)
})
```